---
- hosts: 172.31.52.45
  become: yes
  tasks: 
  - include_tasks: myfile.yml

  - name: i want to create a directory
    file:
      path: /home/lakki/myfolder
      state: directory

  - name: i want to copy testfile
    copy:
      src: mytestfile
      dest: /home/lakki/myfolder/mytestfile
  
  - name: install apache2 webserver
    apt:
     name: apache2
     state: present
    notify: restart webserver 

  - name: i want to copy index files into node
    template:
      src: myindex.j2
      dest: /var/www/html/index.html   

  - name: i want download internet(romote) files
    get_url:
      url: https://github.com/Lpurushotham/myAnsible-git-practice07-07-26/blob/main/javainstall.yml
      dest: /home/lakki/myfolder/javainstall.yml
      force_basic_auth: yes

  handlers:
  - nmae: restart webserver
    service:
      name: apache2
      state: restarted

