---
- name: i want to deploy java app
  get_url:
     src: https://myvarfile03dec24.s3.us-east-2.amazonaws.com/login.war
     dest: /opt/tomcat/apache-tomcat-10.1.57/webapps/login.war
     force_basic_auth: yes
     